### ISSUE TITLE
Is horizon = 1 possible?

### ISSUE THREAD

**Issue by craig3141** [jankrepl/deepdow#144]
Thanks for deepdow, which I'm trying to understand.  

I ran your getting started example code, but with 
`lookback, gap, horizon = 40, 2, 1`
rather than
`lookback, gap, horizon = 40, 2, 20`
and it produced test_loss=nan.

Is there something wrong with setting horizon to 1?

Many thanks!

**Comment by jankrepl** [comment]
@craig3141 Thanks for your interest.

There should be nothing wrong with it:)

**Comment by craig3141** [comment]
Ok, thanks.  But then test_loss is always nan and the code fails.  I put this example in https://colab.research.google.com/drive/1Xik7EM0uCfUiQ-Q-lXzQkp8ujBShqztm?usp=sharing.  Please advise.  Thanks!

**Comment by craig3141** [comment]
So, is there anything that can be done to make the usable for horizon=1?

**Comment by jankrepl** [comment]
@craig3141 sorry for a late response.

I actually take back what I said above. Certain losses (e.g. ShareRatio) will need more than 1 sample in order to obtain legal values (otherwise there will be division by zero).


However, if you only use  the loss/metric `MeanReturn` things should work. 

Hope that helps:)

**Comment by craig3141** [comment]
Of course, thank you!
